var searchData=
[
  ['path_0',['path',['../getting_started_picosdk.html#autotoc_md73',1,'1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path'],['../getting_started_cubemx.html#autotoc_md47',1,'1. Add CMake modules provided by CMRX into CMake module path']]],
  ['pc_1',['pc',['../structExceptionFrameFP.html#a2284e86b5e94105fc506cbf0079131df',1,'ExceptionFrameFP::pc'],['../structExceptionFrame.html#a0eefca46cfc007207520ff8a7b23f332',1,'ExceptionFrame::pc']]],
  ['pending_5fnotifications_2',['pending_notifications',['../structNotificationObject.html#a314f4b8525154216bbbdc1cfc67476b9',1,'NotificationObject']]],
  ['pendsv_5fhandler_3',['PendSV_Handler',['../group__arch__arm__os.html#ga6303e1f258cbdc1f970ce579cc015623',1,'cortex.c']]],
  ['philosophy_4',['Philosophy',['../md_UNIT__TESTING.html#autotoc_md81',1,'']]],
  ['pico_20sdk_5',['3. Configuring CMRX kernel to use Pico-SDK',['../getting_started_picosdk.html#autotoc_md75',1,'']]],
  ['pico_20sdk_20integration_6',['2. Configuring Pico-SDK integration',['../getting_started_picosdk.html#autotoc_md74',1,'']]],
  ['pico_20sdk_20into_20cmake_20module_20path_7',['1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path',['../getting_started_picosdk.html#autotoc_md73',1,'']]],
  ['pico_20sdk_20project_8',['pico sdk project',['../getting_started_picosdk.html',1,'HOWTO: Integrating CMRX into Pico-SDK project'],['../getting_started_picosdk.html#autotoc_md72',1,'Integrating CMRX into Pico-SDK project']]],
  ['pop_5fexception_5fframe_9',['pop_exception_frame',['../group__arch__arm__cortex.html#gad4a222a4d28fa7a5cfff3a7660353361',1,'pop_exception_frame(ExceptionFrame *frame, unsigned args, bool fp_active):&#160;cortex.c'],['../group__arch__arm__syscall.html#gad4a222a4d28fa7a5cfff3a7660353361',1,'pop_exception_frame(ExceptionFrame *frame, unsigned args, bool fp_active):&#160;cortex.c']]],
  ['port_10',['port',['../group__arch__arm.html',1,'ARM port'],['../group__arch__linux.html',1,'Linux port']]],
  ['port_20implementation_20sources_11',['Port implementation sources',['../group__arch__arch.html#sources',1,'']]],
  ['power_20management_12',['Asynchronous delays involving power management',['../group__api__timing.html#async_delay',1,'']]],
  ['precise_20synchronous_20delays_13',['Precise synchronous delays',['../group__api__timing.html#sync_delay',1,'']]],
  ['prerequisites_14',['prerequisites',['../getting_started_picosdk.html#autotoc_md66',1,'Prerequisites'],['../getting_started_cubemx.html#autotoc_md32',1,'Prerequisites']]],
  ['priority_15',['priority',['../structOS__thread__create__t.html#a101f5f58e48c5b90a973d0f63c2a5b0b',1,'OS_thread_create_t::priority'],['../structOS__thread__t.html#abde22ec841a589ba96cc6bc54f9eabb5',1,'OS_thread_t::priority']]],
  ['priority_5finvalid_16',['PRIORITY_INVALID',['../group__os__sched.html#ga1c0157588be40efb99fc590662e237ae',1,'sched.c']]],
  ['priority_5fmax_17',['PRIORITY_MAX',['../group__os__sched.html#gaa95d03c8fe4c7467a8e475748cbf67e1',1,'sched.c']]],
  ['procedure_20calls_18',['procedure calls',['../group__api__rpc.html',1,'Remote Procedure Calls'],['../group__os__rpc.html',1,'Remote Procedure Calls'],['../rpc_intro.html',1,'Remote Procedure Calls']]],
  ['process_19',['process',['../structOS__thread__create__t.html#a127e8c42cb74786a4b675eaae222c0ae',1,'OS_thread_create_t']]],
  ['process_5fcount_20',['process_count',['../group__arch__linux__impl.html#gad607d3bf724355c6474cb14a5ad9663d',1,'static.c']]],
  ['process_5fid_21',['process_id',['../structOS__thread__t.html#aa3ea786a749ff514c3362f8dbbed81d9',1,'OS_thread_t']]],
  ['process_5ft_22',['Process_t',['../group__api.html#ga36958e2082eecb09f367fa4aa3a9a84d',1,'defines.h']]],
  ['processing_23',['Transactional Processing',['../txn_intro.html',1,'overview']]],
  ['project_24',['project',['../getting_started_cubemx.html',1,'HOWTO: Integrating CMRX into CubeMX project'],['../getting_started_picosdk.html',1,'HOWTO: Integrating CMRX into Pico-SDK project'],['../getting_started_cubemx.html#autotoc_md45',1,'Integrating CMRX into CubeMX project'],['../getting_started_picosdk.html#autotoc_md72',1,'Integrating CMRX into Pico-SDK project'],['../getting_started_picosdk.html#autotoc_md76',1,'Linking CMRX to the project'],['../getting_started_cubemx.html#autotoc_md55',1,'Linking CMRX to the project']]],
  ['project_20and_20getting_20cmrx_20source_25',['Generating project and getting CMRX source',['../getting_started_cubemx.html#autotoc_md43',1,'']]],
  ['project_20settings_26',['Basic CubeMX project settings',['../getting_started_cubemx.html#autotoc_md39',1,'']]],
  ['project_20skeleton_27',['Creating Project Skeleton',['../getting_started_picosdk.html#autotoc_md70',1,'']]],
  ['project_20skeleton_20with_20cubemx_28',['Creating project skeleton with CubeMX',['../getting_started_cubemx.html#autotoc_md35',1,'']]],
  ['properties_29',['Transaction engine properties',['../txn_intro.html#autotoc_md65',1,'']]],
  ['protection_30',['protection',['../group__arch__arm__nvic.html',1,'Memory protection'],['../group__arch__arm__mpu.html',1,'Memory protection'],['../group__os__mpu.html',1,'Memory protection']]],
  ['provided_20by_20cmrx_20and_20pico_20sdk_20into_20cmake_20module_20path_31',['1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path',['../getting_started_picosdk.html#autotoc_md73',1,'']]],
  ['provided_20by_20cmrx_20into_20cmake_20module_20path_32',['1. Add CMake modules provided by CMRX into CMake module path',['../getting_started_cubemx.html#autotoc_md47',1,'']]],
  ['provider_33',['provider',['../group__aux__cm__ipi.html',1,'Cortex-M generic IPI provider'],['../group__arch__linux__timing.html',1,'Linux timing provider'],['../group__aux__systick.html',1,'SysTick-Based Timing Provider']]],
  ['provider_20api_34',['Timing provider API',['../group__api__timing.html',1,'']]],
  ['push_5fexception_5fframe_35',['push_exception_frame',['../group__arch__arm__cortex.html#gae810f95e12c75c23d3b87ee2199c9436',1,'push_exception_frame(ExceptionFrame *frame, unsigned args, bool fp_active):&#160;cortex.c'],['../group__arch__arm__syscall.html#gae810f95e12c75c23d3b87ee2199c9436',1,'push_exception_frame(ExceptionFrame *frame, unsigned args, bool fp_active):&#160;cortex.c']]]
];
