var searchData=
[
  ['a_20rpc_20server_0',['Becoming a RPC server',['../rpc_intro.html#autotoc_md37',1,'']]],
  ['abstraction_1',['Communication abstraction',['../group__bsw__com.html',1,'']]],
  ['add_20cmake_20modules_20provided_20by_20cmrx_20and_20pico_20sdk_20into_20cmake_20module_20path_2',['1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path',['../getting_started_picosdk.html#autotoc_md66',1,'']]],
  ['add_20cmake_20modules_20provided_20by_20cmrx_20into_20cmake_20module_20path_3',['1. Add CMake modules provided by CMRX into CMake module path',['../getting_started_cubemx.html#autotoc_md45',1,'']]],
  ['add_5fapplication_4',['add_application()',['../cmrx-cmake.html#autotoc_md23',1,'']]],
  ['add_5ffirmware_5',['add_firmware()',['../cmrx-cmake.html#autotoc_md22',1,'']]],
  ['adding_20blinky_20application_20to_20the_20build_6',['adding blinky application to the build',['../getting_started_picosdk.html#autotoc_md72',1,'Adding blinky application to the build'],['../getting_started_cubemx.html#autotoc_md59',1,'Adding blinky application to the build']]],
  ['address_7',['address',['../structNotificationObject.html#a8ad4157961a23de02fde431a55d98388',1,'NotificationObject']]],
  ['adjustment_20tool_8',['Linker script adjustment tool',['../dev_env.html#autotoc_md60',1,'']]],
  ['advantages_20of_20rpc_20mechanism_9',['Advantages of RPC mechanism',['../rpc_intro.html#autotoc_md46',1,'']]],
  ['aliases_10',['ARM MPU register aliases',['../group__arm__mpu__registers.html',1,'']]],
  ['allocated_11',['allocated',['../structQueueObject.html#abbfe25c2f320b5911a1782c38ad8dc23',1,'QueueObject']]],
  ['allocations_12',['allocations',['../structOS__stack__t.html#acdd99296ece572e929831ab286622c45',1,'OS_stack_t']]],
  ['always_5finline_13',['ALWAYS_INLINE',['../group__arch__arm__cortex.html#gaa1dec568e79152c892dcf63f445cbd7a',1,'cortex.h']]],
  ['anatomy_20of_20cmrx_20port_14',['Anatomy of CMRX port',['../group__arch__arch.html#anatomy',1,'']]],
  ['and_20getting_20cmrx_20source_15',['Generating project and getting CMRX source',['../getting_started_cubemx.html#autotoc_md41',1,'']]],
  ['and_20header_20directories_16',['Source and header directories',['../dev_env.html#autotoc_md58',1,'']]],
  ['and_20pico_20sdk_20into_20cmake_20module_20path_17',['1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path',['../getting_started_picosdk.html#autotoc_md66',1,'']]],
  ['and_20read_20only_20data_18',['Code and read-only data',['../mem_model.html#autotoc_md25',1,'']]],
  ['api_19',['api',['../group__api.html',1,'Kernel API'],['../group__api__standard.html',1,'Standard API'],['../group__api__timing.html',1,'Timing provider API']]],
  ['application_20',['application',['../getting_started_picosdk.html#autotoc_md71',1,'Creating the blinky application'],['../getting_started_cubemx.html#autotoc_md53',1,'Creating the blinky application'],['../getting_started_picosdk.html#autotoc_md73',1,'Flashing the application'],['../getting_started_cubemx.html#autotoc_md61',1,'Flashing the application']]],
  ['application_20to_20the_20build_21',['application to the build',['../getting_started_picosdk.html#autotoc_md72',1,'Adding blinky application to the build'],['../getting_started_cubemx.html#autotoc_md59',1,'Adding blinky application to the build']]],
  ['arch_22',['arch',['../structOS__thread__t.html#a333d54de491449262dd86a09227dc7f9',1,'OS_thread_t']]],
  ['arch_5fstate_5ft_23',['Arch_State_t',['../structArch__State__t.html',1,'']]],
  ['architecture_20support_24',['Architecture support',['../group__arch.html',1,'']]],
  ['arm_20mpu_20ctrl_20fields_25',['ARM MPU CTRL fields',['../group__arm__mpu__ctrl.html',1,'']]],
  ['arm_20mpu_20rasr_20fields_26',['ARM MPU RASR fields',['../group__arm__mpu__rars.html',1,'']]],
  ['arm_20mpu_20rbar_20fields_27',['ARM MPU RBAR fields',['../group__arm__mpu__rbar.html',1,'']]],
  ['arm_20mpu_20register_20aliases_28',['ARM MPU register aliases',['../group__arm__mpu__registers.html',1,'']]],
  ['arm_20port_29',['ARM port',['../group__arch__arm.html',1,'']]],
  ['assertions_30',['Assertions',['../group__util__assert.html',1,'']]],
  ['asynchronous_20delays_20involving_20power_20management_31',['Asynchronous delays involving power management',['../group__api__timing.html#async_delay',1,'']]]
];
