var searchData=
[
  ['id_0',['id',['../structSyscall__Entry__t.html#ac3473bf96a2024c57cf6fdafd216ac6b',1,'Syscall_Entry_t']]],
  ['implementation_1',['implementation',['../rpc_intro.html#autotoc_md20',1,'Define service implementation'],['../group__api__rpc.html#gaac2c999e12c83857c3437c413cb7d47c',1,'IMPLEMENTATION:&#160;implementation.h'],['../group__arch__arm__os.html',1,'OS services implementation'],['../group__arch__arm__rpc.html',1,'RPC implementation'],['../group__arch__arm__sched.html',1,'Scheduler implementation'],['../group__arch__arm__signal.html',1,'Signals implementation'],['../group__arch__arm__syscall.html',1,'System calls implementation']]],
  ['implementation_20of_20rpc_20interfaces_2',['Implementation of RPC interfaces',['../group__api__rpc.html#api_rpc_implementation',1,'']]],
  ['implementation_20sources_3',['Port implementation sources',['../group__arch__arch.html#sources',1,'']]],
  ['implementation_5fof_4',['IMPLEMENTATION_OF',['../group__api__rpc.html#ga3467c0dc3f1f95bb00289609f2ce35f8',1,'implementation.h']]],
  ['initialization_5',['initialization',['../group__arch__arm__static.html',1,'Static initialization'],['../group__api__init.html',1,'Static initialization']]],
  ['instance_6',['INSTANCE',['../group__api__rpc.html#gac79f9e6f9c7223d603a5ac7365617ea7',1,'implementation.h']]],
  ['instances_7',['RPC service instances',['../group__api__rpc.html#api_rpc_instances',1,'']]],
  ['integrating_20cmrx_20into_20cubemx_20project_8',['integrating cmrx into cubemx project',['../getting_started_cubemx.html',1,'HOWTO: Integrating CMRX into CubeMX project'],['../getting_started_cubemx.html#autotoc_md15',1,'Integrating CMRX into CubeMX project']]],
  ['integrating_20cmrx_20into_20pico_20sdk_20project_9',['integrating cmrx into pico sdk project',['../getting_started_picosdk.html',1,'HOWTO: Integrating CMRX into Pico-SDK project'],['../getting_started_picosdk.html#autotoc_md40',1,'Integrating CMRX into Pico-SDK project']]],
  ['integrating_20vendor_20sdks_10',['Integrating vendor SDKs',['../hal_integration.html',1,'overview']]],
  ['integration_11',['integration',['../getting_started_cubemx.html#autotoc_md19',1,'2. Configure CubeMX integration'],['../getting_started_picosdk.html#autotoc_md42',1,'2. Configuring Pico-SDK integration']]],
  ['interface_12',['RPC interface',['../rpc_intro.html#autotoc_md11',1,'']]],
  ['interfaces_13',['interfaces',['../rpc_intro.html#autotoc_md16',1,'Declare interfaces'],['../group__api__rpc.html#api_rpc_implementation',1,'Implementation of RPC interfaces']]],
  ['interfaces_20vtables_14',['RPC interfaces (vtables)',['../group__api__rpc.html#api_rpc_interface',1,'']]],
  ['interrupt_20service_20routines_15',['interrupt service routines',['../group__api__isr.html',1,'Interrupt Service Routines'],['../group__os__isr.html',1,'Interrupt service routines']]],
  ['interrupts_16',['Interrupts',['../exec_model.html#autotoc_md27',1,'']]],
  ['interval_17',['interval',['../structTimerEntry__t.html#a2f45a4b2fcffd30370f2159d80311b00',1,'TimerEntry_t']]],
  ['into_20cmake_20module_20path_18',['into cmake module path',['../getting_started_picosdk.html#autotoc_md41',1,'1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path'],['../getting_started_cubemx.html#autotoc_md17',1,'1. Add CMake modules provided by CMRX into CMake module path']]],
  ['into_20cubemx_20project_19',['into cubemx project',['../getting_started_cubemx.html',1,'HOWTO: Integrating CMRX into CubeMX project'],['../getting_started_cubemx.html#autotoc_md15',1,'Integrating CMRX into CubeMX project']]],
  ['into_20pico_20sdk_20project_20',['into pico sdk project',['../getting_started_picosdk.html',1,'HOWTO: Integrating CMRX into Pico-SDK project'],['../getting_started_picosdk.html#autotoc_md40',1,'Integrating CMRX into Pico-SDK project']]],
  ['introduction_21',['Introduction',['../index.html',1,'']]],
  ['involving_20power_20management_22',['Asynchronous delays involving power management',['../group__api__timing.html#async_delay',1,'']]],
  ['io_23',['Memory-mapped IO',['../mem_model.html#autotoc_md7',1,'']]],
  ['ipi_20provider_24',['Cortex-M generic IPI provider',['../group__aux__cm__ipi.html',1,'']]],
  ['irq_5fdisable_25',['irq_disable',['../group__api__notify.html#ga46328777c39260415d888507d2671c98',1,'irq_disable(uint32_t irq):&#160;irq.c'],['../group__api__signal.html#ga46328777c39260415d888507d2671c98',1,'irq_disable(uint32_t irq):&#160;irq.c']]],
  ['irq_5fenable_26',['irq_enable',['../group__api__notify.html#ga8a318eb1486d9a157e128a92ef7a6c75',1,'irq_enable(uint32_t irq):&#160;irq.c'],['../group__api__signal.html#ga8a318eb1486d9a157e128a92ef7a6c75',1,'irq_enable(uint32_t irq):&#160;irq.c']]],
  ['is_5fperiodic_27',['is_periodic',['../group__os__timer.html#gabc0c9f6d25c5678e6c4c9d88d1edb9bd',1,'timer.c']]],
  ['isr_5fkill_28',['isr_kill',['../group__os__isr.html#gabbc12f9850a82cd7f598e577efbee4bc',1,'isr_kill(Thread_t thread_id, uint32_t signal):&#160;isr.c'],['../group__api__isr.html#gabbc12f9850a82cd7f598e577efbee4bc',1,'isr_kill(Thread_t thread_id, uint32_t signal):&#160;isr.c']]],
  ['isr_5fnotify_5fobject_29',['isr_notify_object',['../group__api__isr.html#ga05d9f276f0bfd526208afa466e89d4b1',1,'isr_notify_object(const void *object):&#160;isr.c'],['../group__os__isr.html#ga05d9f276f0bfd526208afa466e89d4b1',1,'isr_notify_object(const void *object):&#160;isr.c']]],
  ['item_5fsize_30',['item_size',['../group__aux__queue.html#gaf7ce592d2117e17be583562a544e0f6e',1,'Queue']]]
];
