var searchData=
[
  ['c_20headers_0',['C headers',['../group__arch__arch.html#headers',1,'']]],
  ['calling_20rpc_20service_1',['Calling RPC service',['../rpc_intro.html#autotoc_md14',1,'']]],
  ['calls_2',['calls',['../group__api__rpc.html',1,'Remote Procedure Calls'],['../group__os__rpc.html',1,'Remote Procedure Calls'],['../rpc_intro.html',1,'Remote Procedure Calls'],['../group__os__syscall.html',1,'System calls']]],
  ['calls_20implementation_3',['System calls implementation',['../group__arch__arm__syscall.html',1,'']]],
  ['cancel_5ftimed_5fevent_4',['cancel_timed_event',['../group__os__timer.html#gafd631293a404e992816aaa99e85c2625',1,'timer.c']]],
  ['cmake_20functions_5',['CMake functions',['../dev_env.html#autotoc_md18',1,'']]],
  ['cmake_20script_6',['CMake script',['../group__arch__arch.html#script',1,'']]],
  ['cmrx_7',['Obtain dependencies and CMRX',['../getting_started.html#autotoc_md0',1,'']]],
  ['cmrx_20port_8',['Anatomy of CMRX port',['../group__arch__arch.html#anatomy',1,'']]],
  ['cmsis_20helper_9',['CMSIS helper',['../hal_integration.html#autotoc_md21',1,'']]],
  ['code_10',['Organization of the Code',['../dev_code_organization.html',1,'overview']]],
  ['code_20and_20read_20only_20data_11',['Code and read-only data',['../mem_model.html#autotoc_md2',1,'']]],
  ['com_5fnotification_12',['COM_NOTIFICATION',['../group__bsw__com.html#ga0046e741f355150b05ac97f456e39482',1,'com.h']]],
  ['comchannel_13',['ComChannel',['../structComChannel.html',1,'']]],
  ['comchannelvmt_14',['ComChannelVMT',['../structComChannelVMT.html',1,'']]],
  ['communication_20abstraction_15',['Communication abstraction',['../group__bsw__com.html',1,'']]],
  ['comnotification_16',['ComNotification',['../structComNotification.html',1,'']]],
  ['comnotificationvmt_17',['ComNotificationVMT',['../structComNotificationVMT.html',1,'']]],
  ['comsink_18',['ComSink',['../structComSink.html',1,'']]],
  ['comsinkvmt_19',['ComSinkVMT',['../structComSinkVMT.html',1,'']]],
  ['comsource_20',['ComSource',['../structComSource.html',1,'']]],
  ['comsourcevmt_21',['ComSourceVMT',['../structComSourceVMT.html',1,'']]],
  ['concepts_22',['Basic concepts',['../concepts.html',1,'overview']]],
  ['configuration_23',['Kernel runtime configuration',['../group__os__config.html',1,'']]],
  ['constants_20for_20errors_24',['Named constants for errors',['../group__api__errors.html',1,'']]],
  ['context_20switching_25',['Context switching',['../group__os__context.html',1,'']]],
  ['core_26',['core',['../group__os__sched.html#ga2057e79833f71e7a4793d51bc2dca106',1,'core:&#160;sched.c'],['../group__os__kernel.html',1,'Kernel core']]],
  ['corelocal_20h_27',['corelocal.h',['../group__arch__arch.html#corelocal_h',1,'']]],
  ['cortex_20m_20support_20routines_28',['Cortex-M support routines',['../group__arch__arm__cortex.html',1,'']]],
  ['ctrl_20fields_29',['ARM MPU CTRL fields',['../group__arm__mpu__ctrl.html',1,'']]]
];
