var searchData=
[
  ['c_20file_0',['Creating main.c file',['../getting_started_picosdk.html#autotoc_md45',1,'']]],
  ['c_20headers_1',['C headers',['../group__arch__arch.html#headers',1,'']]],
  ['calling_20rpc_20service_2',['Calling RPC service',['../rpc_intro.html#autotoc_md19',1,'']]],
  ['calls_3',['calls',['../rpc_intro.html',1,'Remote Procedure Calls'],['../group__api__rpc.html',1,'Remote Procedure Calls'],['../group__os__rpc.html',1,'Remote Procedure Calls'],['../group__os__syscall.html',1,'System calls']]],
  ['calls_20implementation_4',['System calls implementation',['../group__arch__arm__syscall.html',1,'']]],
  ['caveats_5',['Transaction caveats',['../txn_intro.html#autotoc_md29',1,'']]],
  ['cb_5fsyscall_5fnotify_5fobject_6',['cb_syscall_notify_object',['../group__os__notify.html#ga777174f11e68a4644f69c31bc737ce10',1,'notify.c']]],
  ['cb_5fthread_5fjoin_5fnotify_7',['cb_thread_join_notify',['../group__os__sched.html#gac9b76e4b0629693553a999dd77dabc96',1,'sched.c']]],
  ['cmake_20functions_8',['CMake functions',['../dev_env.html#autotoc_md34',1,'']]],
  ['cmake_20modules_20provided_20by_20cmrx_20and_20pico_20sdk_20into_20cmake_20module_20path_9',['1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path',['../getting_started_picosdk.html#autotoc_md41',1,'']]],
  ['cmake_20modules_20provided_20by_20cmrx_20into_20cmake_20module_20path_10',['1. Add CMake modules provided by CMRX into CMake module path',['../getting_started_cubemx.html#autotoc_md20',1,'']]],
  ['cmake_20script_11',['CMake script',['../group__arch__arch.html#script',1,'']]],
  ['cmrx_20and_20pico_20sdk_20into_20cmake_20module_20path_12',['1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path',['../getting_started_picosdk.html#autotoc_md41',1,'']]],
  ['cmrx_20into_20cmake_20module_20path_13',['1. Add CMake modules provided by CMRX into CMake module path',['../getting_started_cubemx.html#autotoc_md20',1,'']]],
  ['cmrx_20into_20cubemx_20project_14',['cmrx into cubemx project',['../getting_started_cubemx.html',1,'HOWTO: Integrating CMRX into CubeMX project'],['../getting_started_cubemx.html#autotoc_md18',1,'Integrating CMRX into CubeMX project']]],
  ['cmrx_20into_20pico_20sdk_20project_15',['cmrx into pico sdk project',['../getting_started_picosdk.html',1,'HOWTO: Integrating CMRX into Pico-SDK project'],['../getting_started_picosdk.html#autotoc_md40',1,'Integrating CMRX into Pico-SDK project']]],
  ['cmrx_20kernel_20to_20use_20cubemx_16',['3. Configure the CMRX kernel to use CubeMX',['../getting_started_cubemx.html#autotoc_md23',1,'']]],
  ['cmrx_20kernel_20to_20use_20pico_20sdk_17',['3. Configuring CMRX kernel to use Pico-SDK',['../getting_started_picosdk.html#autotoc_md43',1,'']]],
  ['cmrx_20port_18',['Anatomy of CMRX port',['../group__arch__arch.html#anatomy',1,'']]],
  ['cmrx_20source_19',['Generating project and getting CMRX source',['../getting_started_cubemx.html#autotoc_md16',1,'']]],
  ['cmrx_20to_20the_20project_20',['cmrx to the project',['../getting_started_cubemx.html#autotoc_md25',1,'Linking CMRX to the project'],['../getting_started_picosdk.html#autotoc_md44',1,'Linking CMRX to the project']]],
  ['cmrx_5farch_5fsmp_5fsupported_21',['CMRX_ARCH_SMP_SUPPORTED',['../group__os__config.html#ga54ec6c4dfec8397771e101eb023fd91a',1,'kernel.h']]],
  ['cmrx_5fkernel_5ftracing_22',['CMRX_KERNEL_TRACING',['../group__os__config.html#ga46a3ec2ee0c0ead945b1185c467024c5',1,'kernel.h']]],
  ['cmrx_5fshutdown_5fhandler_23',['cmrx_shutdown_handler',['../group__arch__arm__sched.html#gaa1fe4414a243f61c85e0a1d2fbd01440',1,'sched.c']]],
  ['cmsis_20helper_24',['CMSIS helper',['../hal_integration.html#autotoc_md38',1,'']]],
  ['code_25',['Organization of the Code',['../dev_code_organization.html',1,'overview']]],
  ['code_20and_20read_20only_20data_26',['Code and read-only data',['../mem_model.html#autotoc_md0',1,'']]],
  ['com_5fnotification_27',['COM_NOTIFICATION',['../group__bsw__com.html#ga0046e741f355150b05ac97f456e39482',1,'com.h']]],
  ['comchannel_28',['ComChannel',['../structComChannel.html',1,'']]],
  ['comchannelvmt_29',['ComChannelVMT',['../structComChannelVMT.html',1,'']]],
  ['communication_20abstraction_30',['Communication abstraction',['../group__bsw__com.html',1,'']]],
  ['comnotification_31',['ComNotification',['../structComNotification.html',1,'']]],
  ['comnotificationvmt_32',['ComNotificationVMT',['../structComNotificationVMT.html',1,'']]],
  ['comsink_33',['ComSink',['../structComSink.html',1,'']]],
  ['comsinkvmt_34',['ComSinkVMT',['../structComSinkVMT.html',1,'']]],
  ['comsource_35',['ComSource',['../structComSource.html',1,'']]],
  ['comsourcevmt_36',['ComSourceVMT',['../structComSourceVMT.html',1,'']]],
  ['concepts_37',['Basic concepts',['../concepts.html',1,'overview']]],
  ['configuration_38',['Kernel runtime configuration',['../group__os__config.html',1,'']]],
  ['configure_20cubemx_20integration_39',['2. Configure CubeMX integration',['../getting_started_cubemx.html#autotoc_md22',1,'']]],
  ['configure_20the_20cmrx_20kernel_20to_20use_20cubemx_40',['3. Configure the CMRX kernel to use CubeMX',['../getting_started_cubemx.html#autotoc_md23',1,'']]],
  ['configuring_20cmrx_20kernel_20to_20use_20pico_20sdk_41',['3. Configuring CMRX kernel to use Pico-SDK',['../getting_started_picosdk.html#autotoc_md43',1,'']]],
  ['configuring_20gpios_42',['Configuring GPIOs',['../getting_started_cubemx.html#autotoc_md14',1,'']]],
  ['configuring_20pico_20sdk_20integration_43',['2. Configuring Pico-SDK integration',['../getting_started_picosdk.html#autotoc_md42',1,'']]],
  ['configuring_20the_20core_44',['Configuring the core',['../getting_started_cubemx.html#autotoc_md11',1,'']]],
  ['constants_20for_20errors_45',['Named constants for errors',['../group__api__errors.html',1,'']]],
  ['container_5fof_46',['CONTAINER_OF',['../group__util.html#ga818b9cca761fe7bc18e4e417da772976',1,'util.h']]],
  ['content_47',['content',['../structQueue.html#a7c3d232b52fdd2ff01ed578fed30400e',1,'Queue']]],
  ['context_20switching_48',['Context switching',['../group__os__context.html',1,'']]],
  ['core_49',['core',['../getting_started_cubemx.html#autotoc_md11',1,'Configuring the core'],['../group__os__sched.html#ga2057e79833f71e7a4793d51bc2dca106',1,'core:&#160;sched.c'],['../group__os__sched.html#ga2057e79833f71e7a4793d51bc2dca106',1,'core:&#160;sched.c'],['../structOS__thread__create__t.html#ac0224e5ced934ff094125a1ba6295a6d',1,'OS_thread_create_t::core'],['../group__os__kernel.html',1,'Kernel core']]],
  ['core_5fid_50',['core_id',['../structOS__thread__t.html#a92a48d3f33bbb1d5bac8fa215bfb2b92',1,'OS_thread_t']]],
  ['coreid_51',['coreid',['../group__arch__arch.html#ga08c83fbec4a92bba591402c53805f345',1,'corelocal.h']]],
  ['corelocal_20h_52',['corelocal.h',['../group__arch__arch.html#corelocal_h',1,'']]],
  ['cortex_20m_20generic_20ipi_20provider_53',['Cortex-M generic IPI provider',['../group__aux__cm__ipi.html',1,'']]],
  ['cortex_20m_20support_20routines_54',['Cortex-M support routines',['../group__arch__arm__cortex.html',1,'']]],
  ['create_55',['create',['../structQueueServiceInterface.html#ab2ff0a185bef735e1546727006fce031',1,'QueueServiceInterface']]],
  ['creating_20main_20c_20file_56',['Creating main.c file',['../getting_started_picosdk.html#autotoc_md45',1,'']]],
  ['creating_20project_20skeleton_57',['Creating Project Skeleton',['../getting_started_picosdk.html#autotoc_md39',1,'']]],
  ['creating_20project_20skeleton_20with_20cubemx_58',['Creating project skeleton with CubeMX',['../getting_started_cubemx.html#autotoc_md7',1,'']]],
  ['creating_20the_20blinky_20application_59',['creating the blinky application',['../getting_started_cubemx.html#autotoc_md28',1,'Creating the blinky application'],['../getting_started_picosdk.html#autotoc_md46',1,'Creating the blinky application']]],
  ['critical_20section_20to_20transaction_60',['From critical section to transaction',['../txn_intro.html#autotoc_md27',1,'']]],
  ['ctrl_20fields_61',['ARM MPU CTRL fields',['../group__arm__mpu__ctrl.html',1,'']]],
  ['cubemx_62',['cubemx',['../getting_started_cubemx.html#autotoc_md23',1,'3. Configure the CMRX kernel to use CubeMX'],['../getting_started_cubemx.html#autotoc_md7',1,'Creating project skeleton with CubeMX']]],
  ['cubemx_20hal_20tweaks_63',['CubeMX HAL tweaks',['../getting_started_cubemx.html#autotoc_md31',1,'']]],
  ['cubemx_20integration_64',['2. Configure CubeMX integration',['../getting_started_cubemx.html#autotoc_md22',1,'']]],
  ['cubemx_20project_65',['cubemx project',['../getting_started_cubemx.html',1,'HOWTO: Integrating CMRX into CubeMX project'],['../getting_started_cubemx.html#autotoc_md18',1,'Integrating CMRX into CubeMX project']]],
  ['cubemx_20project_20settings_66',['Basic CubeMX project settings',['../getting_started_cubemx.html#autotoc_md9',1,'']]]
];
