var searchData=
[
  ['path_0',['1. Add CMake modules provided by CMRX into CMake module path',['../getting_started.html#autotoc_md19',1,'']]],
  ['pc_1',['pc',['../structExceptionFrame.html#a0eefca46cfc007207520ff8a7b23f332',1,'ExceptionFrame']]],
  ['pending_5fnotifications_2',['pending_notifications',['../structNotificationObject.html#a314f4b8525154216bbbdc1cfc67476b9',1,'NotificationObject']]],
  ['pendsv_5fhandler_3',['PendSV_Handler',['../group__arch__arm__os.html#ga6303e1f258cbdc1f970ce579cc015623',1,'cortex.c']]],
  ['pop_5fexception_5fframe_4',['pop_exception_frame',['../group__arch__arm__cortex.html#ga0deb287bdcb87be51cdb7440df6ad7e5',1,'cortex.h']]],
  ['port_5',['port',['../group__arch__arch.html#anatomy',1,'Anatomy of CMRX port'],['../group__arch__arm.html',1,'ARM port']]],
  ['port_20implementation_20sources_6',['Port implementation sources',['../group__arch__arch.html#sources',1,'']]],
  ['porting_20layer_7',['Porting layer',['../group__arch__arch.html',1,'']]],
  ['power_20management_8',['Asynchronous delays involving power management',['../group__api__timing.html#async_delay',1,'']]],
  ['precise_20synchronous_20delays_9',['Precise synchronous delays',['../group__api__timing.html#sync_delay',1,'']]],
  ['prerequisites_10',['Prerequisites',['../getting_started.html#autotoc_md2',1,'']]],
  ['priority_11',['priority',['../structOS__thread__create__t.html#a101f5f58e48c5b90a973d0f63c2a5b0b',1,'OS_thread_create_t::priority'],['../structOS__thread__t.html#abde22ec841a589ba96cc6bc54f9eabb5',1,'OS_thread_t::priority']]],
  ['priority_5finvalid_12',['PRIORITY_INVALID',['../group__os__sched.html#ga1c0157588be40efb99fc590662e237ae',1,'sched.c']]],
  ['priority_5fmax_13',['PRIORITY_MAX',['../group__os__sched.html#gaa95d03c8fe4c7467a8e475748cbf67e1',1,'sched.c']]],
  ['procedure_20calls_14',['procedure calls',['../group__api__rpc.html',1,'Remote Procedure Calls'],['../group__os__rpc.html',1,'Remote Procedure Calls'],['../rpc_intro.html',1,'Remote Procedure Calls']]],
  ['process_15',['process',['../structOS__thread__create__t.html#a127e8c42cb74786a4b675eaae222c0ae',1,'OS_thread_create_t']]],
  ['process_5fid_16',['process_id',['../structOS__thread__t.html#aa3ea786a749ff514c3362f8dbbed81d9',1,'OS_thread_t']]],
  ['process_5ft_17',['Process_t',['../group__api.html#ga36958e2082eecb09f367fa4aa3a9a84d',1,'defines.h']]],
  ['processing_18',['Transactional Processing',['../txn_intro.html',1,'overview']]],
  ['project_19',['project',['../getting_started.html#autotoc_md17',1,'Integrating CMRX into CubeMX project'],['../getting_started.html#autotoc_md24',1,'Linking CMRX to the project']]],
  ['project_20and_20getting_20cmrx_20source_20',['Generating project and getting CMRX source',['../getting_started.html#autotoc_md15',1,'']]],
  ['project_20settings_21',['Basic CubeMX project settings',['../getting_started.html#autotoc_md9',1,'']]],
  ['project_20skeleton_20with_20cubemx_22',['Creating project skeleton with CubeMX',['../getting_started.html#autotoc_md7',1,'']]],
  ['properties_23',['Transaction engine properties',['../txn_intro.html#autotoc_md33',1,'']]],
  ['protection_24',['protection',['../group__arch__arm__mpu.html',1,'Memory protection'],['../group__arch__arm__nvic.html',1,'Memory protection'],['../group__os__mpu.html',1,'Memory protection']]],
  ['provided_20by_20cmrx_20into_20cmake_20module_20path_25',['1. Add CMake modules provided by CMRX into CMake module path',['../getting_started.html#autotoc_md19',1,'']]],
  ['provider_26',['provider',['../group__aux__cm__ipi.html',1,'Cortex-M generic IPI provider'],['../group__aux__systick.html',1,'SysTick-Based Timing Provider']]],
  ['provider_20api_27',['Timing provider API',['../group__api__timing.html',1,'']]],
  ['push_5fexception_5fframe_28',['push_exception_frame',['../group__arch__arm__cortex.html#ga2c8bf166b828e4a26c74bc974774510f',1,'cortex.h']]]
];
