var searchData=
[
  ['a_20rpc_20server_0',['Becoming a RPC server',['../rpc_intro.html#autotoc_md46',1,'']]],
  ['abstract_20machine_1',['abstract machine',['../group__arch__arch.html',1,'Abstract machine'],['../group__arch__arch.html#anatomy',1,'Anatomy of CMRX abstract machine']]],
  ['abstraction_2',['Communication abstraction',['../group__bsw__com.html',1,'']]],
  ['add_20cmake_20modules_20provided_20by_20cmrx_20and_20pico_20sdk_20into_20cmake_20module_20path_3',['1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path',['../getting_started_picosdk.html#autotoc_md57',1,'']]],
  ['add_20cmake_20modules_20provided_20by_20cmrx_20into_20cmake_20module_20path_4',['1. Add CMake modules provided by CMRX into CMake module path',['../getting_started_cubemx.html#autotoc_md38',1,'']]],
  ['add_5fapplication_5',['add_application()',['../cmrx-cmake.html#autotoc_md23',1,'']]],
  ['add_5ffirmware_6',['add_firmware()',['../cmrx-cmake.html#autotoc_md22',1,'']]],
  ['adding_20blinky_20application_20to_20the_20build_7',['adding blinky application to the build',['../getting_started_picosdk.html#autotoc_md66',1,'Adding blinky application to the build'],['../getting_started_cubemx.html#autotoc_md48',1,'Adding blinky application to the build']]],
  ['address_8',['address',['../structNotificationObject.html#a8ad4157961a23de02fde431a55d98388',1,'NotificationObject']]],
  ['adjustment_20tool_9',['Linker script adjustment tool',['../dev_env.html#autotoc_md72',1,'']]],
  ['advantages_20of_20rpc_20mechanism_10',['Advantages of RPC mechanism',['../rpc_intro.html#autotoc_md54',1,'']]],
  ['aliases_11',['ARM MPU register aliases',['../group__arm__mpu__registers.html',1,'']]],
  ['allocated_12',['allocated',['../structQueueObject.html#abbfe25c2f320b5911a1782c38ad8dc23',1,'QueueObject']]],
  ['allocations_13',['allocations',['../structOS__stack__t.html#acdd99296ece572e929831ab286622c45',1,'OS_stack_t']]],
  ['always_5finline_14',['ALWAYS_INLINE',['../group__arch__arm__cortex.html#gaa1dec568e79152c892dcf63f445cbd7a',1,'cortex.h']]],
  ['anatomy_20of_20cmrx_20abstract_20machine_15',['Anatomy of CMRX abstract machine',['../group__arch__arch.html#anatomy',1,'']]],
  ['and_20getting_20cmrx_20source_16',['Generating project and getting CMRX source',['../getting_started_cubemx.html#autotoc_md34',1,'']]],
  ['and_20header_20directories_17',['Source and header directories',['../dev_env.html#autotoc_md71',1,'']]],
  ['and_20pico_20sdk_20into_20cmake_20module_20path_18',['1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path',['../getting_started_picosdk.html#autotoc_md57',1,'']]],
  ['and_20read_20only_20data_19',['Code and read-only data',['../mem_model.html#autotoc_md26',1,'']]],
  ['api_20',['api',['../group__api.html',1,'Kernel API'],['../group__api__standard.html',1,'Standard API'],['../group__api__timing.html',1,'Timing provider API']]],
  ['application_21',['application',['../getting_started_picosdk.html#autotoc_md64',1,'Creating the blinky application'],['../getting_started_cubemx.html#autotoc_md42',1,'Creating the blinky application'],['../getting_started_cubemx.html#autotoc_md50',1,'Flashing the application'],['../getting_started_picosdk.html#autotoc_md67',1,'Flashing the application']]],
  ['application_20to_20the_20build_22',['application to the build',['../getting_started_picosdk.html#autotoc_md66',1,'Adding blinky application to the build'],['../getting_started_cubemx.html#autotoc_md48',1,'Adding blinky application to the build']]],
  ['arch_23',['arch',['../structOS__thread__t.html#a333d54de491449262dd86a09227dc7f9',1,'OS_thread_t']]],
  ['arch_5fstate_5ft_24',['Arch_State_t',['../structArch__State__t.html',1,'']]],
  ['architecture_20support_25',['Architecture support',['../group__arch.html',1,'']]],
  ['arm_20mpu_20ctrl_20fields_26',['ARM MPU CTRL fields',['../group__arm__mpu__ctrl.html',1,'']]],
  ['arm_20mpu_20rasr_20fields_27',['ARM MPU RASR fields',['../group__arm__mpu__rars.html',1,'']]],
  ['arm_20mpu_20rbar_20fields_28',['ARM MPU RBAR fields',['../group__arm__mpu__rbar.html',1,'']]],
  ['arm_20mpu_20register_20aliases_29',['ARM MPU register aliases',['../group__arm__mpu__registers.html',1,'']]],
  ['arm_20port_30',['ARM port',['../group__arch__arm.html',1,'']]],
  ['assertions_31',['Assertions',['../group__util__assert.html',1,'']]],
  ['asynchronous_20delays_20involving_20power_20management_32',['Asynchronous delays involving power management',['../group__api__timing.html#async_delay',1,'']]]
];
