var searchData=
[
  ['a_20rpc_20server_0',['Becoming a RPC server',['../rpc_intro.html#autotoc_md17',1,'']]],
  ['abstraction_1',['Communication abstraction',['../group__bsw__com.html',1,'']]],
  ['add_20cmake_20modules_20provided_20by_20cmrx_20and_20pico_20sdk_20into_20cmake_20module_20path_2',['1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path',['../getting_started_picosdk.html#autotoc_md41',1,'']]],
  ['add_20cmake_20modules_20provided_20by_20cmrx_20into_20cmake_20module_20path_3',['1. Add CMake modules provided by CMRX into CMake module path',['../getting_started_cubemx.html#autotoc_md14',1,'']]],
  ['adding_20blinky_20application_20to_20the_20build_4',['adding blinky application to the build',['../getting_started_picosdk.html#autotoc_md47',1,'Adding blinky application to the build'],['../getting_started_cubemx.html#autotoc_md35',1,'Adding blinky application to the build']]],
  ['address_5',['address',['../structNotificationObject.html#a8ad4157961a23de02fde431a55d98388',1,'NotificationObject']]],
  ['adjustment_20tool_6',['Linker script adjustment tool',['../dev_env.html#autotoc_md34',1,'']]],
  ['advantages_20of_20rpc_20mechanism_7',['Advantages of RPC mechanism',['../rpc_intro.html#autotoc_md23',1,'']]],
  ['aliases_8',['ARM MPU register aliases',['../group__arm__mpu__registers.html',1,'']]],
  ['allocated_9',['allocated',['../structQueueObject.html#abbfe25c2f320b5911a1782c38ad8dc23',1,'QueueObject']]],
  ['allocations_10',['allocations',['../structOS__stack__t.html#acdd99296ece572e929831ab286622c45',1,'OS_stack_t']]],
  ['always_5finline_11',['ALWAYS_INLINE',['../group__arch__arm__cortex.html#gaa1dec568e79152c892dcf63f445cbd7a',1,'cortex.h']]],
  ['anatomy_20of_20cmrx_20port_12',['Anatomy of CMRX port',['../group__arch__arch.html#anatomy',1,'']]],
  ['and_20getting_20cmrx_20source_13',['Generating project and getting CMRX source',['../getting_started_cubemx.html#autotoc_md11',1,'']]],
  ['and_20header_20directories_14',['Source and header directories',['../dev_env.html#autotoc_md32',1,'']]],
  ['and_20pico_20sdk_20into_20cmake_20module_20path_15',['1. Add CMake modules provided by CMRX and Pico-SDK into CMake module path',['../getting_started_picosdk.html#autotoc_md41',1,'']]],
  ['and_20read_20only_20data_16',['Code and read-only data',['../mem_model.html#autotoc_md1',1,'']]],
  ['api_17',['api',['../group__api.html',1,'Kernel API'],['../group__api__standard.html',1,'Standard API'],['../group__api__timing.html',1,'Timing provider API']]],
  ['application_18',['application',['../getting_started_cubemx.html#autotoc_md29',1,'Creating the blinky application'],['../getting_started_picosdk.html#autotoc_md46',1,'Creating the blinky application'],['../getting_started_cubemx.html#autotoc_md37',1,'Flashing the application'],['../getting_started_picosdk.html#autotoc_md48',1,'Flashing the application']]],
  ['application_20to_20the_20build_19',['application to the build',['../getting_started_cubemx.html#autotoc_md35',1,'Adding blinky application to the build'],['../getting_started_picosdk.html#autotoc_md47',1,'Adding blinky application to the build']]],
  ['arch_5fstate_5ft_20',['Arch_State_t',['../structArch__State__t.html',1,'']]],
  ['architecture_20support_21',['Architecture support',['../group__arch.html',1,'']]],
  ['arm_20mpu_20ctrl_20fields_22',['ARM MPU CTRL fields',['../group__arm__mpu__ctrl.html',1,'']]],
  ['arm_20mpu_20rasr_20fields_23',['ARM MPU RASR fields',['../group__arm__mpu__rars.html',1,'']]],
  ['arm_20mpu_20rbar_20fields_24',['ARM MPU RBAR fields',['../group__arm__mpu__rbar.html',1,'']]],
  ['arm_20mpu_20register_20aliases_25',['ARM MPU register aliases',['../group__arm__mpu__registers.html',1,'']]],
  ['arm_20port_26',['ARM port',['../group__arch__arm.html',1,'']]],
  ['assertions_27',['Assertions',['../group__util__assert.html',1,'']]],
  ['asynchronous_20delays_20involving_20power_20management_28',['Asynchronous delays involving power management',['../group__api__timing.html#async_delay',1,'']]]
];
