#pragma once
/** @defgroup aux_riscv_pico_timer RISC-V Pico SDK Machine-Timer-Based Timing Provider
 * @ingroup libs
 * Ready-to-use implementation of @ref api_timing for RP2350 RISC-V cores. The
 * kernel tick is generated by the RISC-V machine timer (`mtime`/`mtimecmp`),
 * accessed through Pico SDK's `hardware/riscv_platform_timer.h`.
 *
 * Call `timing_provider_setup()` once, before @ref os_start(), with the tick
 * period in milliseconds. It only stores the period; the timer is armed when
 * the kernel first calls @ref timing_provider_schedule(). The tick period is
 * fixed, so the kernel's tickless feature is not used.
 *
 * The library also defines `cmrx_machine_timer_handler()`, which the
 * `quirks/pico-sdk-riscv` machine-timer interrupt handler calls on every tick.
 * @{
 */

void timing_provider_setup(int interval_ms);

void timing_provider_schedule(long delay_us);

void timing_provider_delay(long delay_us);

/** Machine timer tick handler.
 * Re-arms the timer and notifies the kernel. Called by the
 * `quirks/pico-sdk-riscv` machine timer ISR; not meant to be called by
 * applications.
 */
void cmrx_machine_timer_handler(void);

/** @} */
