get_property(CMRX_BINARIES GLOBAL PROPERTY CMRX_BINARY_LIST)
foreach(BINARY ${CMRX_BINARIES})
	_patch_linker_script(${DEVICE} ${BINARY})
	get_property(APP_LIBRARIES TARGET ${BINARY} PROPERTY LINK_LIBRARIES)
	foreach(LIB ${APP_LIBRARIES})
		if (TARGET ${LIB})
			get_property(LIB_IS_APPLICATION TARGET ${LIB} PROPERTY CMRX_IS_APPLICATION)
			if ("${LIB_IS_APPLICATION}" EQUAL "1")
				_gen_app_linker_script(${LIB} ${BINARY})
			endif()
		endif()
	endforeach()
	message("** ${APP_LIBRARIES}")
endforeach()


