name: Onboard to MemBrowse

on:
  workflow_dispatch:
    inputs:
      num_commits:
        description: 'Number of commits to process'
        required: true
        default: '100'
        type: string

jobs:
  load-targets:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Load target matrix
        id: set-matrix
        run: echo "matrix=$(jq -c '.' .github/membrowse-targets.json)" >> $GITHUB_OUTPUT

  onboard:
    needs: load-targets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.load-targets.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          fetch-depth: 0

      - name: Prepare Cross-Toolchain Environment
        if: matrix.target_name != 'linux'
        uses: carlosperate/arm-none-eabi-gcc-action@v1
        with:
          release: '12.2.Rel1'

      - name: Checkout Integration Tests
        uses: actions/checkout@v4.1.6
        with:
          repository: ventZl/cmrx-integration-tests
          path: _integ

      - name: Checkout Raspberry Pi Pico SDK
        if: matrix.target_name == 'rp2040'
        uses: actions/checkout@v4.1.6
        with:
          repository: raspberrypi/pico-sdk
          path: _integ/rp2040-pico-sdk/pico-sdk

      - name: Link CMRX source
        run: rm -rf _integ/${{ matrix.source_dir }}/cmrx && ln -s $GITHUB_WORKSPACE _integ/${{ matrix.source_dir }}/cmrx

      - name: Run MemBrowse Onboard Action
        uses: membrowse/membrowse-action/onboard-action@v1
        with:
          target_name: ${{ matrix.target_name }}
          num_commits: ${{ github.event.inputs.num_commits }}
          build_script: ${{ matrix.build_cmd }}
          elf: ${{ matrix.elf }}
          ld: ${{ matrix.ld }}
          map_file: ${{ matrix.map_file }}
          linker_vars: ${{ matrix.linker_vars }}
          binary_search: 'true'
          api_key: ${{ secrets.MEMBROWSE_API_KEY }}
          api_url: ${{ vars.MEMBROWSE_API_URL }}
