name: Pull Request Unit Tests
on: 
  pull_request:
    branches: [ master ]

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4.1.6
       with:
        submodules: 'true'

     - name: Configure and Build Unit Tests
       uses: threeal/cmake-action@main
       with:
        c-compiler: gcc
        run-build: true
        build-dir: unit_tests
        options: CMRX_UNIT_TESTS=ON

     - name: Run unit Tests
       run: cmake --build unit_tests -- test
