name: 'Build: stm32g4'

on:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'push' && github.sha || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
     - name: Prepare Cross-Toolchain Environment
       uses: carlosperate/arm-none-eabi-gcc-action@v1
       with:
         release: '12.2.Rel1'

     - name: Checkout repository
       uses: actions/checkout@v4.1.6
       with:
         fetch-depth: 0

     - name: Checkout Integration Tests
       uses: actions/checkout@v4.1.6
       with:
         repository: ventZl/cmrx-integration-tests
         path: _integ

     - name: Link CMRX source
       run: rm -rf _integ/stm32g4-cubemx/cmrx && ln -s $GITHUB_WORKSPACE _integ/stm32g4-cubemx/cmrx

     - name: Configure Integration Test Build
       uses: threeal/cmake-action@main
       with:
        run-build: false
        source-dir: _integ/stm32g4-cubemx
        build-dir: build
        args: -DCMRX_UNIT_TESTS=OFF -DCMAKE_BUILD_TYPE=Debug

     - name: Pre-build Integration Test
       run: make -C build
       continue-on-error: true

     - name: Build Integration Test
       run: make -C build

     - name: Run MemBrowse analysis
       uses: membrowse/membrowse-action@v1
       with:
         target_name: stm32g4
         elf: build/stm32g4-cubemx.elf
         ld: _integ/stm32g4-cubemx/stm32g491cctx_flash.ld
         map_file: build/stm32g4-cubemx.map
         api_key: ${{ secrets.MEMBROWSE_API_KEY }}
         api_url: ${{ vars.MEMBROWSE_API_URL }}
         verbose: INFO
